name: "run a node install"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
permissions:
  contents: write
  pull-requests: write
jobs:
  run-an-install:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Install-dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci --save
          else
          npm i
          fi
      - name: nodefix
        run: npm ci --save
