name: "run a node install"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
permissions:
  contents: write
  pull-requests: write
jobs:
  run-an-install:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: run-an-install
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g npm
