name: 'node.js installer'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
permissions:
    contents: write
    pull-requests: write
jobs:
  install:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        # Set always-auth in npmrc.
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions.
        check-latest: true
